Minor fixes in /opt/iredmail/bin/fail2ban/banned_db.

diff --git a/config/opt/iredmail/bin/fail2ban/banned_db b/config/opt/iredmail/bin/fail2ban/banned_db
--- a/config/opt/iredmail/bin/fail2ban/banned_db
+++ b/config/opt/iredmail/bin/fail2ban/banned_db
@@ -97,12 +97,17 @@ DELETE FROM ${DB_TABLE} WHERE jail='${_jail}';
 EOF
     fi
 
-    [[ X"$?" == X'0' ]] && echo "Cleaned up."
+    [[ X"$?" == X'0' ]] && echo "All IP addresses have been removed."
 elif [[ X"${_action}" == X"unban_db" ]]; then
     # Call fail2ban-client to unban given IP address(es).
     tmp_file="$(mktemp)"
 
-    ${CMD_SQL} -e "SELECT jail,ip FROM ${DB_TABLE} WHERE remove=1" | grep -v '^jail' >> ${tmp_file}
+    # Exclude extra info on output, just leave jail/ip.
+    (${CMD_SQL} <<EOF
+SELECT jail, ip FROM ${DB_TABLE} WHERE remove=1;
+EOF
+) | grep -Ev '(jail.*ip|\--|\(|^$)' | tr -d '|' >> ${tmp_file}
+
     while read jail ip; do
         # Avoid SQL injection: don't allow whitespace, ';', quotes in
         # jail name and IP address.
@@ -116,8 +121,10 @@ elif [[ X"${_action}" == X"unban_db" ]]; then
             continue
         fi
 
-        fail2ban-client set ${jail} unbanip ${ip}
-        [[ X"$?" == X'0' ]] && echo "Unbanned: jail '${jail}', IP '${ip}'."
+        # fail2ban-client returns number of processed rows on command line,
+        # let's discard it to avoid noise/confusion.
+        fail2ban-client set ${jail} unbanip ${ip} >/dev/null
+        [[ X"$?" == X'0' ]] && echo "Unbanned ${ip} from jail [${jail}]."
     done < ${tmp_file}
     rm -f ${tmp_file} &>/dev/null
 fi
